### ISSUE TITLE
Public install page for Xamarin builds

### ISSUE THREAD

**Issue by bykovme** [bitrise-io/steps-deploy-to-bitrise-io#22]
Xamarin build produces both APK & IPA file and there are 2 separate install pages for the files generated. Nevertheless, there is only one variable for public installation page ($BITRISE_PUBLIC_INSTALL_PAGE_URL ) in the output and only one link to installation page is assigned there  (points to APK in my case), while I need on the next steps to know the links to both installation pages to inform the testers in slack.
Could you produce additional separate variables for APK & IPA on this step?

**Comment by viktorbenei** [comment]
Thanks for the feature request!

Right now you can do this by using multiple Deploy to Bitrise.io steps, pointing it to the IPA / APK directly, instead of to the directory where the files are stored.

In the future we plan to add a new environment variable which will include a list of the public install pages, instead of just one item.

**Comment by bykovme** [comment]
Thanks for the tip with multiple deploy steps and looking forward for the new version of the step :)

**Comment by freever** [comment]
Yeah the multiple deploy steps option is a good one!

**Comment by viktorbenei** [comment]
A new option will be available, introduced in https://github.com/bitrise-io/steps-deploy-to-bitrise-io/pull/54 ; the `BITRISE_PUBLIC_INSTALL_PAGE_URL_MAP` output will include a map of all the generated public install pages.

Not released yet, but should be soon (after merging https://github.com/bitrise-io/steps-deploy-to-bitrise-io/pull/55 & publishing a new version) :)
