### ISSUE TITLE
Add a file-filter option, ex: to be able to upload only *.ipa files from the specified directory

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-io/steps-deploy-to-bitrise-io#3]

**Comment by ghaabor** [comment]
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

@viktorbenei  please let us know if we can help with anything and we'll reopen this issue!
