### ISSUE TITLE
Deploy failed, error: failed to create sdk model, error: No path provided

### ISSUE THREAD

**Issue by ivarvermeulen** [bitrise-io/steps-deploy-to-bitrise-io#39]
I'm using the deploy to bitrise step to upload APK files generated within a cordova project. It correctly detects the APK files, however during upload an error is triggered: Deploy failed, error: failed to create sdk model, error: No path provided

+------------------------------------------------------------------------------+

| (2) deploy-to-bitrise-io@1.3.5                                               |
+------------------------------------------------------------------------------+
| id: deploy-to-bitrise-io                                                     |
| version: 1.3.5                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2017-07-05T01:29:42-07:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
Configs:
- BuildURL: https://www.bitrise.io/build/XXXXXXXXXX
- APIToken: XXXXXXXXXXX
- IsCompress: false
- DeployPath: phonegap/platforms/android/build/outputs/apk/
- NotifyUserGroups: everyone
- NotifyEmailList: 
- IsPublicPageEnabled: true
Deploying the content of the Deploy directory separately
List of files to deploy
- /Users/vagrant/git/phonegap/platforms/android/build/outputs/apk/android-armv7-release.apk
- /Users/vagrant/git/phonegap/platforms/android/build/outputs/apk/android-x86-release.apk
Deploying files
Uploading apk file: /Users/vagrant/git/phonegap/platforms/android/build/outputs/apk/android-armv7-release.apk
analyzing apk
Deploy failed, error: failed to create sdk model, error: No path provided

**Comment by viktorbenei** [comment]
Thanks for reporting @ivarvermeulen !

@godrei assigned, please check!

**Comment by godrei** [comment]
Hi @ivarvermeulen ,
thanks for the report!
Did you run the mentioned failed build on bitrise.io or on your local machine?
The error log is not too informative, but it seems the step does not find `ANDROID_HOME` environment, thats why it can not initialise the sdk model.

**Comment by viktorbenei** [comment]
Good catch @godrei ! From the paths it seems the build ran on bitrise.io (`/Users/vagrant/git`) but it indeed might be the wrong stack.

@ivarvermeulen did you run this on a Xamarin stack? The standard Xcode stacks don't include the Android tools.

**Comment by ivarvermeulen** [comment]
@viktorbenei @godrei i'm running it on the xcode stack, however I do install android tools on the xcode stack:

#!/bin/bash
# fail if any commands fails
set -e
# debug log
set -x

# write your script here
brew tap caskroom/cask
brew cask install android-sdk
brew install gradle

**Comment by ivarvermeulen** [comment]
Also just added these commands after the android-sdk install

export ANDROID_SDK_ROOT=/usr/local/share/android-sdk
export PATH=$PATH:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools

But still fails, will try to use xamarin stack now but had other issue in the past using that stack.

**Comment by ivarvermeulen** [comment]
Using the xamarin stack, the android build fails:

Error: Could not find an installed version of Gradle either in Android Studio,
or on your system to install the gradle wrapper. Please include gradle 
in your path, or install Android Studio

**Comment by ivarvermeulen** [comment]
Issue is solved by installing gradle on the xamarin stack.

**Comment by viktorbenei** [comment]
Hi @ivarvermeulen , glad to hear you managed to solve the issue :)

Just a couple of notes:

## For your first solution, using an Xcode stack and installing Android SDK manually

What you have to do there is to specify and **expose** the `ANDROID_HOME` env var.

Something like this should work:

```
export ANDROID_HOME=/usr/local/share/android-sdk
envman add --key ANDROID_HOME --value "$ANDROID_HOME"
```

More info about `envman` and how you can expose env vars from one step so that subsequent steps will have access to that env var: http://devcenter.bitrise.io/tips-and-tricks/expose-environment-variable/

## Second solution, using the Xamarin stack

The thing is, Gradle should not be required. How do you build your project? Our **Gradle Runner** steps work with `gradlew`, the gradle wrapper, which is the official solution to ensure the right gradle version is available. Related discussion:

- https://discuss.bitrise.io/t/how-to-update-grade-version-from-script/1115/2?u=viktorbenei
- http://blog.bitrise.io/2016/08/17/new-gradle-runner-version-gradlew-path-is-now-required.html
