### ISSUE TITLE
Ignore on absent directory

### ISSUE THREAD

**Issue by PaulWoitaschek** [bitrise-io/steps-deploy-to-bitrise-io#76]
I have a general `post` workflow which pushes the cashes and artifacts to bitrise.
Now I have one workflow where I don't have produced an artifact.
It would be great if upon an absent directory, bitrise would just log a message that here was nothing to deploy and ignore the failure.

**Comment by trapacska** [comment]
Hey @PaulWoitaschek !

You can set `is_skippable` to true for the step in your bitrise.yml, then it will be skipped in case of a failure. Will that help in this issue?

**Comment by PaulWoitaschek** [comment]
Is there no way to do this from the UI? I don't use the `yml` config.

**Comment by bitce** [comment]
Hi @PaulWoitaschek,  this can be done from the UI with this toggle button:
<img width="967" alt="screenshot 2018-11-13 at 14 54 18" src="https://user-images.githubusercontent.com/40164469/48417854-1f1c0800-e754-11e8-8131-0e66f42c131a.png">

Although If I understand correctly, you'll want the following steps to run, so this should be toggled to the green check state.

**Comment by PaulWoitaschek** [comment]
I don't care about the state of the previous step. I just don't want my whole build to fail because the `_post` step found no directory to upload.

Are you sure the flag would help here?

**Comment by bitce** [comment]
Sorry, not really sure since you did not provide much detail here, I was assuming based on the description that you are faced with an issue that the cache doesn't get pushed due to the Deploy step failing expectedly. Setting this for the Cache step would definitely help in this specific scenario.

Unfortunately, there isn't a way to not have the step fail on absent directory, you may submit a feature request to us about this, although I'm not entirely sure what use case would it fit, could you explain that to us? If you are aware that the directory will be empty, couldn't you simply not include the step?

**Comment by PaulWoitaschek** [comment]
Don't mind I just added a script step creating the directory.
